name = "Fimbul"
uuid = "cac51d78-27de-4708-bd2b-bd13a82f652b"
authors = ["Øystein Klemetsdal"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
